version: '3'
services:
  jenkins:
    build:
      target: jenkins_local
    ports:
      - 8080:8080
    volumes:
      - ./jenkins/casc_local.yaml:/home/jenkins/casc.yaml
      - ./jobs:/home/jenkins/workspace/LocalSeed
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/home/jenkins